// This file is auto-generated by Android Data Binding.
// Do not modify this file -- YOUR CHANGES WILL BE ERASED!
// This file must be generated by the Android build system.
// Please rebuild the project to generate this file.

// Note: This is a placeholder file. In a real Android project,
// this file would be automatically generated by the Android build system
// when ViewBinding is enabled in build.gradle.

// The actual binding classes will be generated based on the XML layout files
// and will contain references to all views with IDs in the layout.